#!/bin/bash


function tim_install() {
	wp plugin install --activate "https://github.com/kllmanu/tim/archive/refs/heads/master.zip"
	exit
}

function tim_uninstall() {
	wp plugin deactivate --uninstall tim
	exit
}

[[ "$1" == "-i" ]] && tim_install
[[ "$1" == "-u" ]] && tim_uninstall

while true; do 
	jless "$tim/context.json"
	sleep 0.2
done
